bundler_args: --without development:production

rvm:
  - 1.9.2

before_script:
  - "psql -c 'create database rubyagile_test;' -U postgres >/dev/null"
  - "cp config/database.yml.sample config/database.yml"

env: RAILS_ENV=test
script: bundle exec rake spec
