language: ruby
rvm: 2.0.0
bundler_args: --without development:production
before_install: gem update bundler
before_script: bundle exec rake db:create db:migrate RAILS_ENV=test
script: bundle exec rake
